spring:
  application:
    name: peony

  datasource:
    url: ${POSTGRES_URL:}
    username: ${POSTGRES_USER:}
    password: ${POSTGRES_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
